#This is small change made to the ros_controllers and
#the post was made a good note 

# controller_manager_ns: controller_manager
# controller_list:
# - name: ur5_1_controller
#   action_ns: follow_joint_trajectory
#   type: FollowJointTrajectory
#   default: true
#   joints:
#   - ur5_elbow_joint 
#   - ur5_shoulder_lift_joint 
#   - ur5_shoulder_pan_joint 
#   - ur5_wrist_1_joint 
#   - ur5_wrist_2_joint 
#   - ur5_wrist_3_joint




#This is what they put later on piazza:
# Controller to attach Gazebo Controller to Moveit! to allow Moveit! to control UR5 in Gazebo.

controller_manager_ns: /
controller_list:
  - name: ur5_1_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
    - ur5_shoulder_pan_joint
    - ur5_shoulder_lift_joint
    - ur5_elbow_joint
    - ur5_wrist_1_joint
    - ur5_wrist_2_joint
    - ur5_wrist_3_joint